production:
  adapter: mysql2
  username: localisto
  password: BbMUPZ82Vy5uY2FL
  database: localistoapp
  host: localhost
  pool: 5
  encoding: utf8  
  timeout: 5000

development:
  adapter: mysql2
  database: localisto1-25
  username: root
  password: root
  host: 127.0.0.1
  encoding: utf8  
  port: 8889
  pool: 5