production:
  adapter: mysql2
  username: localisto
  password: BbMUPZ82Vy5uY2FL
  database: localistoapp
  host: localhost
# socket: /var/lib/mysql/mysql.sock
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: localisto9-3
  username: rooto
  password: rooto
  port: 8889
  pool: 5