production:
  adapter: mysql2
  user: localistoapp
  password: mBuYXa7Z2GZhFUyE
  database: localistoapp
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: localisto9-3
  user: root
  password: root
  port: 8889
  pool: 5